<center>Smith Waterman Algorithm</center>

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import Bio
from Bio.Seq import Seq

In [2]:
def smith_waterman(ref_seq,query,match,mismatch,W1):

    #Defining matrix (n+1)(m+1)
    H = np.zeros([len(ref_seq) + 1,len(query) + 1])
    zero = 0

    #Defining scoring matrix
    for i in range(1,len(ref_seq) + 1):
        for j in range(1,len(query) + 1):
            if ref_seq[i-1] == query[j-1]:
                H[i,j] = H[i-1,j-1] + match
            else:
                H[i,j] = max(H[i-1,j] - W1,H[i,j-1] - W1,H[i-1,j-1] + mismatch,zero)

    #Isolating Max-value and creating empty aligned sequences
    ref_aligned = []
    query_aligned = []
    i, j = np.unravel_index(H.argmax(),H.shape)
    ref_aligned.append(ref_seq[i-1])
    query_aligned.append(query[j-1])
    score = H[i,j]

    #Tracing back from largest value
    while H[i,j]!=0:
        directions = max(H[i-1,j-1],H[i-1,j],H[i,j-1])
        minimal = min(H[i-1,j-1],H[i-1,j],H[i,j-1])
        
        if directions == H[i-1,j-1] and minimal != 0:
            i, j = i-1, j-1
            ref_aligned.append(ref_seq[i-1])
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
            else:
                query_aligned.append('-')
            
            
        elif directions == H[i-1,j] and minimal != 0:
            i, j = i-1, j
            ref_aligned.append(ref_seq[i-1])
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
    
        else:
            i, j = i, j-1
            query_aligned.append(query[j-1])
            if ref_seq[i-1] == query[j-1]:
                ref_aligned.append('-')
    
    length=min(len(ref_seq),len(query))
    similarity=(score/(length*match))*100
    print("Score:", score)
    print('target:',''.join(ref_aligned[::-1]))
    print('query: ',''.join(query_aligned[::-1]))
    print("Query Sequence is",round(similarity),"%","similar to Referance Sequence")
    

        

ref_seq='GTAGAGTTACGAGATAGATGG'
query= 'GTAGTTCGAGGTGAGTAGGTGG' 
match=3
mismatch=-3
W1=2


smith_waterman(ref_seq,query,match,mismatch,W1)               

Score: 34.0
target: -GTAGAGTTACGA--G-ATAGATGG
query:  GGTAGGTT-CGAGGTGA-TAG-TGG
Query Sequence is 54 % similar to Referance Sequence


In [3]:
def smith_waterman(ref_seq,query,match,mismatch,W1):

    #Defining matrix (n+1)(m+1)
    H = np.zeros([len(ref_seq) + 1,len(query) + 1])
    zero = 0

    #Defining scoring matrix
    for i in range(1,len(ref_seq) + 1):
        for j in range(1,len(query) + 1):
            if ref_seq[i-1] == query[j-1]:
                H[i,j] = H[i-1,j-1] + match
            else:
                H[i,j] = max(H[i-1,j] - W1,H[i,j-1] - W1,H[i-1,j-1] + mismatch,zero)

    #Isolating Max-value and creating empty aligned sequences
    ref_aligned = []
    query_aligned = []
    i, j = np.unravel_index(H.argmax(),H.shape)
    ref_aligned.append(ref_seq[i-1])
    query_aligned.append(query[j-1])
    score = H[i,j]

    #Tracing back from largest value
    while H[i,j]!=0:
        directions = max(H[i-1,j-1],H[i-1,j],H[i,j-1])
        minimal = min(H[i-1,j-1],H[i-1,j],H[i,j-1])
        
        if directions == H[i-1,j-1] and minimal != 0:
            i, j = i-1, j-1
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
                ref_aligned.append(ref_seq[i-1])
            elif ref_seq[i-1]!=query[j-1] and H[i-1,j]>H[i,j-1]:
                query_aligned.append('-')
                ref_aligned.append(ref_seq[i])
            else:
                query_aligned.append(query[j])
                ref_aligned.append('-')
            
            
        elif directions == H[i-1,j] and minimal != 0:
            i, j = i-1, j
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
                ref_aligned.append(ref_seq[i-1])
            elif ref_seq[i-1]!=query[j-1] and H[i-1,j]>H[i,j-1]:
                query_aligned.append('-')
                ref_aligned.append(ref_seq[i])
            else:
                query_aligned.append('-')
                ref_aligned.append(ref_seq[i])
    
        else:
            i, j = i, j-1
            
    length=min(len(ref_seq),len(query))
    similarity=(score/(length*match))*100
    print("Score:", score)
    print('target:',''.join(ref_aligned[::-1]),len(ref_aligned))
    print('query: ',''.join(query_aligned[::-1]),len(query_aligned))
    print("Query Sequence is",round(similarity),"%","similar to Referance Sequence")
    print(H)

        

ref_seq='TGTTACGG'
query= 'GGTTGACTA' 
match=3
mismatch=-3
W1=2


smith_waterman(ref_seq,query,match,mismatch,W1)

Score: 13.0
target: GT-AC 5
query:  GTAAC 5
Query Sequence is 54 % similar to Referance Sequence
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  3.  3.  1.  0.  0.  3.  1.]
 [ 0.  3.  3.  1.  1.  6.  4.  2.  1.  0.]
 [ 0.  1.  1.  6.  4.  4.  3.  1.  5.  3.]
 [ 0.  0.  0.  4.  9.  7.  5.  3.  4.  2.]
 [ 0.  0.  0.  2.  7.  6. 10.  8.  6.  7.]
 [ 0.  0.  0.  0.  5.  4.  8. 13. 11.  9.]
 [ 0.  3.  3.  1.  3.  8.  6. 11. 10.  8.]
 [ 0.  3.  6.  4.  2.  6.  5.  9.  8.  7.]]


In [4]:
def smith_waterman(ref_seq,query,match,mismatch,W1):

    #Defining matrix (n+1)(m+1)
    H = np.zeros([len(ref_seq) + 1,len(query) + 1])
    zero = 0

    #Defining scoring matrix
    for i in range(1,len(ref_seq) + 1):
        for j in range(1,len(query) + 1):
            if ref_seq[i-1] == query[j-1]:
                H[i,j] = H[i-1,j-1] + match
            else:
                H[i,j] = max(H[i-1,j] - W1,H[i,j-1] - W1,H[i-1,j-1] + mismatch,zero)

    #Isolating Max-value and creating empty aligned sequences
    ref_aligned = []
    query_aligned = []
    i, j = np.unravel_index(H.argmax(),H.shape)
    ref_aligned.append(ref_seq[i-1])
    query_aligned.append(query[j-1])
    score = H[i,j]

    #Tracing back from largest value
    while H[i,j]!=0:
        directions = max(H[i-1,j-1],H[i-1,j],H[i,j-1])
        minimal = min(H[i-1,j-1],H[i-1,j],H[i,j-1])
        
        if directions == H[i-1,j-1] and minimal != 0:
            i, j = i-1, j-1
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
                ref_aligned.append(ref_seq[i-1])
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.append(ref_seq[i-1])
                query_aligned.append('-')
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.append('-')
                query_aligned.append(query[j-1])
                  
            
        elif directions == H[i-1,j] and minimal != 0:
            i, j = i-1, j
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
                ref_aligned.append(ref_seq[i-1])
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.append(ref_seq[i-1])
                query_aligned.append('-')
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.append('-')
                query_aligned.append(query[j-1])

        
    
        else:
            i, j = i, j-1
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
                ref_aligned.append(ref_seq[i-1])
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.append(ref_seq[i-1])
                query_aligned.append('-')
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.append('-')
                query_aligned.append(query[j-1])

    length=min(len(ref_seq),len(query))
    similarity=(score/(length*match))*100
    print("Score:", score)
    print('target:',''.join(ref_aligned[::-1]))
    print('query: ',''.join(query_aligned[::-1]))
    print("Query Sequence is",round(similarity),"%","similar to Referance Sequence")
    

        

ref_seq='GGGTCTCTATGTGGCTGGCAGGGACCTAGGTACTTG'
query= 'TTTCACTTTTGGGTAAATACATTCTTCATACCAGGACCAGAGGAAAATTCAGACAAAGTAGAAAATGGAAGTCTTTGTGGTGATCAAGAGATTGATAGTATTTGCAGTGCCGAGCGATCAGATAATGACAAGGAATATCTCATACTCACATTATCCAAAAATGATCTTGACAAAGCGAATAAAGACAAGGCCAACCGATACTTTTCTCCAAAT' 
match=3
mismatch=-3
W1=2


smith_waterman(ref_seq,query,match,mismatch,W1)
ref_seq='TGTTACGG'
query='GGTTGACTA'
smith_waterman(ref_seq,query,match,mismatch,W1)

Score: 50.0
target: GG--GGTCTCTATGTGGCTG--CAAG-G---GACCTAGGTACTTTG
query:  GGAAGGTCT-T-TGTGG-TGATCAAGAGATTGA--TAGGTA-TTTG
Query Sequence is 46 % similar to Referance Sequence
Score: 13.0
target: GGTT-AC
query:  GGTTGAC
Query Sequence is 54 % similar to Referance Sequence


In [5]:
def smith_waterman(ref_seq,query,match,mismatch,W1):

    #Defining matrix (n+1)(m+1)
    H = np.zeros([len(ref_seq) + 1,len(query) + 1])
    zero = 0

    #Defining scoring matrix
    for i in range(1,len(ref_seq) + 1):
        for j in range(1,len(query) + 1):
            if ref_seq[i-1] == query[j-1]:
                H[i,j] = H[i-1,j-1] + match
            else:
                H[i,j] = max(H[i-1,j] - W1,H[i,j-1] - W1,H[i-1,j-1] + mismatch,zero)

    #Isolating Max-value and creating empty aligned sequences
    ref_aligned = []
    query_aligned = []
    i, j = np.unravel_index(H.argmax(),H.shape)
    ref_aligned.append(ref_seq[i-1])
    query_aligned.append(query[j-1])
    score = H[i,j]

    #Tracing back from largest value
    while H[i,j]!=0:
        directions = max(H[i-1,j-1],H[i-1,j],H[i,j-1])
        minimal = min(H[i-1,j-1],H[i-1,j],H[i,j-1])
        
        if directions == H[i-1,j-1] and minimal != 0:
            i, j = i-1, j-1
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
                ref_aligned.append(ref_seq[i-1])
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.append(ref_seq[i-1])
                query_aligned.append('-')
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.append('-')
                query_aligned.append(query[j-1])
                  
            
        elif directions == H[i-1,j] and minimal != 0:
            i, j = i-1, j
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
                ref_aligned.append(ref_seq[i-1])
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.append(ref_seq[i-1])
                query_aligned.append('-')
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.append('-')
                query_aligned.append(query[j-1])

        
    
        else:
            i, j = i, j-1
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
                ref_aligned.append(ref_seq[i-1])
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.append(ref_seq[i-1])
                query_aligned.append('-')
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.append('-')
                query_aligned.append(query[j-1])

    length=min(len(ref_seq),len(query))
    similarity=(score/(length*match))*100
    print("Score:", score)
    print('target:',''.join(ref_aligned[::-1]))
    print('query: ',''.join(query_aligned[::-1]))
    print("Query Sequence is",round(similarity),"%","similar to Referance Sequence")
    

        

ref_seq='GGGTCTCTATGTGGCTGGCAGGGACCTAGGTACTTG'
query='TTTCACTTTTGGGTAAATACATTCTTCATACCAGGACCAGAGGAAAATTCAGACAAAGTAGAAAATGGAAGTCTTTGTGGTGATCAAGAGATTGATAGTATTTGCAGTGCCGAGCGATCAGATAATGACAAGGAATATCTCATACTCACATTATCCAAAAATGATCTTGACAAAGCGAATAAAGACAAGGCCAACCGATACTTTTCTCCAAAT' 
match=3
match=3
mismatch=-3
W1=2


smith_waterman(ref_seq,query,match,mismatch,W1)

Score: 50.0
target: GG--GGTCTCTATGTGGCTG--CAAG-G---GACCTAGGTACTTTG
query:  GGAAGGTCT-T-TGTGG-TGATCAAGAGATTGA--TAGGTA-TTTG
Query Sequence is 46 % similar to Referance Sequence


In [6]:
def smith_waterman(ref_seq,query,match,mismatch,W1):

    #Defining matrix (n+1)(m+1)
    H = np.zeros([len(ref_seq) + 1,len(query) + 1])
    zero = 0

    #Defining scoring matrix
    for i in range(1,len(ref_seq) + 1):
        for j in range(1,len(query) + 1):
            if ref_seq[i-1] == query[j-1]:
                H[i,j] = H[i-1,j-1] + match
            else:
                H[i,j] = max(H[i-1,j] - W1,H[i,j-1] - W1,H[i-1,j-1] + mismatch,zero)

    #Isolating Max-value and creating empty aligned sequences
    ref_aligned = []
    query_aligned = []
    i, j = np.unravel_index(H.argmax(),H.shape)
    ref_aligned.append(ref_seq[i-1])
    query_aligned.append(query[j-1])
    score = H[i,j]

    #Tracing back from largest value
    while H[i,j]!=0:
        directions = max(H[i-1,j-1],H[i-1,j],H[i,j-1])
        minimal = min(H[i-1,j-1],H[i-1,j],H[i,j-1])
        
        if directions == H[i-1,j-1] and minimal != 0:
            i, j = i-1, j-1
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
                ref_aligned.append(ref_seq[i-1])
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.append(ref_seq[i-1])
                query_aligned.append('-')
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.append('-')
                query_aligned.append(query[j-1])
                  
            
        elif directions == H[i-1,j] and minimal != 0:
            i, j = i-1, j
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
                ref_aligned.append(ref_seq[i-1])
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.append(ref_seq[i-1])
                query_aligned.append('-')
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.append('-')
                query_aligned.append(query[j-1])

        
    
        else:
            i, j = i, j-1
            if ref_seq[i-1] == query[j-1]:
                query_aligned.append(query[j-1])
                ref_aligned.append(ref_seq[i-1])
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.append(ref_seq[i-1])
                query_aligned.append('-')
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.append('-')
                query_aligned.append(query[j-1])

    length=min(len(ref_seq),len(query))
    similarity=(score/(length*match))*100
    print("Score:", score)
    print('target:',''.join(ref_aligned[::-1]))
    print("|" *len(ref_aligned)+"|")
    print('query: ',''.join(query_aligned[::-1]))
    print("Query Sequence is",round(similarity),"%","similar to Referance Sequence")
    

        

ref_seq='GGGTCTCTATGTGGCTGGCAGGGACCTAGGTACTTG'
query='TTTCACTTTTGGGTAAATACATTCTTCATACCAGGACCAGAGGAAAATTCAGACAAAGTAGAAAATGGAAGTCTTTGTGGTGATCAAGAGATTGATAGTATTTGCAGTGCCGAGCGATCAGATAATGACAAGGAATATCTCATACTCACATTATCCAAAAATGATCTTGACAAAGCGAATAAAGACAAGGCCAACCGATACTTTTCTCCAAAT' 
match=3

match=3
mismatch=-3
W1=2


smith_waterman(ref_seq,query,match,mismatch,W1)

Score: 50.0
target: GG--GGTCTCTATGTGGCTG--CAAG-G---GACCTAGGTACTTTG
|||||||||||||||||||||||||||||||||||||||||||||||
query:  GGAAGGTCT-T-TGTGG-TGATCAAGAGATTGA--TAGGTA-TTTG
Query Sequence is 46 % similar to Referance Sequence


In [7]:
with open('brc2.txt') as f:
    ref_seq = f.read()
with open('protein.txt') as f:
    query= f.read()
ref_seq='GEPSIKRNLLNEFDRIIENQEKSLKASKSTPDGTIKDRRLFMHHVSLEPITCVPFRTTKERQEIQNPNFGTA'
query='GEPSIKRNLLNEFDRIIENQEKSLKASKSTPDGTIKDRRLFMHHVSLEPITCVPFRTTKERQEIQNPNFTAPGQEFLSKSHLYEHLTLEKSSSNLAVSGHPFYQVSA'
match=3
mismatch=-3
W1=2


smith_waterman(ref_seq,query,match,mismatch,W1)

Score: 211.0
target: GEPSIKRNLLNEFDRIIENQEKSLKASKSTPDGTIKDRRLFMHHVSLEPITCVPFRTTKERQEIQNPNFGTA
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
query:  GEPSIKRNLLNEFDRIIENQEKSLKASKSTPDGTIKDRRLFMHHVSLEPITCVPFRTTKERQEIQNPNF-TA
Query Sequence is 98 % similar to Referance Sequence


In [8]:
from Bio import Align
aligner = Align.PairwiseAligner()
aligner.mode='local'
aligner.algorithm
aligner.match_score=3
aligner.mismatch_score=-3
aligner.gap_score=-2
seq_rab='GTAGAGTTACGAGATAGATGG'
seq_kan='GTAGTTCGAGGTGAGTAGGTGG'
alignments = aligner.align(seq_rab, seq_kan)
for alignment in alignments:
    print(alignment)
score = aligner.score(seq_rab, seq_kan)
score
H=np.zeros([5,4])
H

target            0 GTAGAGTTACGAGAT-AG-A--TGG 21
                  0 ||||--||-||||.|-||-|--||| 25
query             0 GTAG--TT-CGAGGTGAGTAGGTGG 22

target            0 GTAGAGTTACGAGAT-AG-A--TGG 21
                  0 |||--|||-||||.|-||-|--||| 25
query             0 GTA--GTT-CGAGGTGAGTAGGTGG 22

target            0 GTAGAGTTACGAGAT-AG-A--TGG 21
                  0 ||--||||-||||.|-||-|--||| 25
query             0 GT--AGTT-CGAGGTGAGTAGGTGG 22

target            0 GTAGAGTTACGAG---A-TAGATGG 21
                  0 ||||--||-||||---|-|||.||| 25
query             0 GTAG--TT-CGAGGTGAGTAGGTGG 22

target            0 GTAGAGTTACGAG---A-TAGATGG 21
                  0 |||--|||-||||---|-|||.||| 25
query             0 GTA--GTT-CGAGGTGAGTAGGTGG 22

target            0 GTAGAGTTACGAG---A-TAGATGG 21
                  0 ||--||||-||||---|-|||.||| 25
query             0 GT--AGTT-CGAGGTGAGTAGGTGG 22

target            0 GTAGAGTTACGA-G--A-TAGATGG 21
                  0 ||||--||-|||-|--|-|||.||| 25
query         

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
def smith_waterman(ref_seq,query,match,mismatch,W1):

    #Defining matrix (n+1)(m+1)
    H = np.zeros([len(ref_seq) + 1,len(query) + 1])
    zero = 0

    #Defining scoring matrix
    for i in range(1,len(ref_seq) + 1):
        for j in range(1,len(query) + 1):
            if ref_seq[i-1] == query[j-1]:
                H[i,j] = H[i-1,j-1] + match
            else:
                H[i,j] = max(H[i-1,j] - W1,H[i,j-1] - W1,H[i-1,j-1] + mismatch,zero)

    #Isolating Max-value and creating empty aligned sequences
    ref_aligned = []
    query_aligned = []
    i, j = np.unravel_index(H.argmax(),H.shape)
    ref_aligned.append(ref_seq[i-1])
    query_aligned.append(query[j-1])
    score = H[i,j]
    markers=[]

    #Tracing back from largest value
    while H[i,j]!=0:
        directions = max(H[i-1,j-1],H[i-1,j],H[i,j-1])
        minimal = min(H[i-1,j-1],H[i-1,j],H[i,j-1])
        
        if directions == H[i-1,j-1] and minimal != 0:
            i, j = i-1, j-1
           
            if ref_seq[i-1] == query[j-1]:
                query_aligned.insert(-1,query[j-1])
                ref_aligned.insert(-1,ref_seq[i-1])
               
                
            
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.insert(-1,ref_seq[i-1])
                query_aligned.insert(-1,'-')
                
    
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.insert(-1,'-')
                query_aligned.insert(-1,query[j-1])
                
            
        elif directions == H[i-1,j] and minimal != 0:
            i, j = i-1, j
            if ref_seq[i-1] == query[j-1]:
                query_aligned.insert(-1,query[j-1])
                ref_aligned.insert(-1,ref_seq[i-1])
                
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.insert(-1,ref_seq[i-1])
                query_aligned.insert(-1,'-')
                
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.insert(-1,'-')
                query_aligned.insert(-1,query[j-1])
                

        
    
        else:
            i, j = i, j-1
            if ref_seq[i-1] == query[j-1]:
                query_aligned.insert(-1,query[j-1])
                ref_aligned.insert(-1,ref_seq[i-1])
                
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]>H[i,j-1]:
                ref_aligned.insert(-1,ref_seq[i-1])
                query_aligned.insert(-1,'-')
                
            elif ref_seq[i-1] != query[j-1] and H[i-1,j]<H[i,j-1]:
                ref_aligned.insert(-1,'-')
                query_aligned.insert(-1,query[j-1])
                

    length=min(len(ref_seq),len(query))
    similarity=(score/(length*match))*100
    print("Score:", score)
    print('target:',''.join(ref_aligned)[::-1])
    print('query: ',''.join(query_aligned)[::-1])
    print("Query Sequence is",round(similarity),"%","similar to Referance Sequence")
    
        

ref_seq='TGTTACGG'
query= 'GGTTGACTA'
match=3
mismatch=-3
W1=2


smith_waterman(ref_seq,query,match,mismatch,W1)
from Bio import Align
aligner = Align.PairwiseAligner()
aligner.mode='local'
aligner.algorithm
aligner.match_score=3
aligner.mismatch_score=-3
aligner.gap_score=-2
seq_rab='MTSSRLWFSLLLAAAFAGRATALWPWPQNFQTSDQRYVLYPNNFQFQYDVSSAAQPGCSVLDEAFQRYRDLLFGSGSWPRPYLTGKRHTLEKNVLVVSVVTPGCNQLPTLESVENYTLTINDDQCLLLSETVWGALRGLETFSQLVWKSAEGTFFINKTEIEDFPRFPHRGLLLDTSRHYLPLSSILDTLDVMAYNKLNVFHWHLVDDPSFPYESFTFPELMRKGSYNPVTHIYTAQDVKEVIEYARLRGIRVLAEFDTPGHTLSWGPGIPGLLTPCYSGSEPSGTFGPVNPSLNNTYEFMSTFFLEVSSVFPDFYLHLGGDEVDFTCWKSNPEIQDFMRKKGFGEDFKQLESFYIQTLLDIVSSYGKGYVVWQEVFDNKVKIQPDTIIQVWREDIPVNYMKELELVTKAGFRALLSAPWYLNRISYGPDWKDFYIVEPLAFEGTPEQKALVIGGEACMWGEYVDNTNLVPRLWPRAGAVAERLWSNKLTSDLTFAYERLSHFRCELLRRGVQAQPLNVGFCEQEFEQT'
seq_kan='MTSSRLWFSLLLAAAFAGRATALWPWPQNFQTSDQRYVLYPNNFQFQYDVSSAAQPGCSVLDEAFQRYRDLLFGSGSWPRPYLTGWPHQAYPVFLGKRHTLEKNVLVVSVVTPGCNQLPTLESVENYTLTINDDQCLLLSETVWGALRGLETFSQLVWKSAEGTFFINKTEIEDFPRFPHRGLLLDTSRHYLPLSSILDTLDVMAYNKLNVFHWHLVDDPSFPYESFTFPELMRKGSYNPVTHIYTAQDVKEVIEYARLRGIRVLAEFDTPGHTLSWGPGIPGLLTPCYSGSEPSGTFGPVNPSLNNTYEFMSTFFLEVSSVFPDFYLHLGGDEVDFTCWKSNPEIQDFMRKKGFGEDFKQLESFYIQTLLDIVSSYGKGYVVWQEVFDNKVKIQPDTIIQVWREDIPVNYMKELELVTKAGFRALLSAPWYLNRISYGPDWKDFYIVEPLAFEGTPEQKALVIGGEACMWGEYVDNTNLVPRLWPRAGAVAERLWSNKLTSDLTFAYERLSHFRCELLRRGVQAQPLNVGFCEQEFEQT'
ref_seq='MTSSRLWFSLLLAAAFAGRATALWPWPQNFQTSDQRYVLYPNNFQFQYDVSSAAQPGCSVLDEAFQRYRDLLFGSGSWPRPYLTGKRHTLEKNVLVV'
query='MTSSRLWFSLLLAAAFAGRATALWPWPQNFQTSDQRYVLYPNNFQFQYDVSSAAQPGCSVLDEAFQRYRDLLFGSGSWPRPYLTGWPHQAYPVFLGK'
seq_rab=ref_seq
seq_kan=query
alignments = aligner.align(seq_rab, seq_kan)
for alignment in alignments:
    print(alignment)
score = aligner.score(seq_rab, seq_kan)
score

Score: 13.0
target: CGGTT-A
query:  CGGTTGA
Query Sequence is 54 % similar to Referance Sequence
target            0 MTSSRLWFSLLLAAAFAGRATALWPWPQNFQTSDQRYVLYPNNFQFQYDVSSAAQPGCSV
                  0 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
query             0 MTSSRLWFSLLLAAAFAGRATALWPWPQNFQTSDQRYVLYPNNFQFQYDVSSAAQPGCSV

target           60 LDEAFQRYRDLLFGSGSWPRPYLTG 85
                 60 ||||||||||||||||||||||||| 85
query            60 LDEAFQRYRDLLFGSGSWPRPYLTG 85



255.0

In [10]:
seq_rab='MTSSRLWFSLLLAAAFAGRATALWPWPQNFQTSDQRYVLYPNNFQFQYDVSSAAQPGCSVLDEAFQRYRDLLFGSGSWPRPYLTGKRHTLEKNVLVVSVVTPGCNQLPTLESVENYTLTINDDQCLLLSETVWGALRGLETFSQLVWKSAEGTFFINKTEIEDFPRFPHRGLLLDTSRHYLPLSSILDTLDVMAYNKLNVFHWHLVDDPSFPYESFTFPELMRKGSYNPVTHIYTAQDVKEVIEYARLRGIRVLAEFDTPGHTLSWGPGIPGLLTPCYSGSEPSGTFGPVNPSLNNTYEFMSTFFLEVSSVFPDFYLHLGGDEVDFTCWKSNPEIQDFMRKKGFGEDFKQLESFYIQTLLDIVSSYGKGYVVWQEVFDNKVKIQPDTIIQVWREDIPVNYMKELELVTKAGFRALLSAPWYLNRISYGPDWKDFYIVEPLAFEGTPEQKALVIGGEACMWGEYVDNTNLVPRLWPRAGAVAERLWSNKLTSDLTFAYERLSHFRCELLRRGVQAQPLNVGFCEQEFEQT'
seq_kan='MASSRLWFSLLLAAALAGRATALWPWPQNIQTSDQRYVLYPNNFQFQYDVSSAAQPGCSVLDEAFQRYRDLLFGSGSWPRPYLTGKRHTLEKNVLVVSVVTPGCNQLPTLESVENYTLTINDDQCLLLSETVWGALRGLETFSQLVWKSAEGTFFINKTEIEDFPRFPHRGLLLDTSRHYLPLSSILDTLDVMAYNKLNVFHWHLVDDPSFPYESFTFPELMRKGSYNPVTHIYTAQDVKEVIEYARLRGIRVLAEFDTPGHTLSWGPGIPGLLTPCYSGSEPSGTFGPVNPSLNNTYEFMSTFFLEVSSVFPDFYLHLGGDEVDFTCWKSNPDIQDFMRKKGFGEDFKQLESFYIQTLLDIVSSYGKGYVVWQEVFDNKVKIRPDTIIQVWREDIPVNYMKELELVTKAGFRALLSAPWYLNRISYGPDWKDFYVVEPLAFEGTPEQKALVIGGEACMWGEYVDNTNLVPRLWPRAGAVAERLWSNKLTSDLTFAYERLSHFRCELLRKSKTKSATGTAAAGCELLRLRSLR'
ref_seq = "GGGTCTCTATGTGGCTGGCAGGGACCTAGGTACTTG"
query= "TTTCACTTTTGGGTAAATACATTCTTCATACCAGGACCAGAGGAAAATTCAGACAAAGTAGAAAATGGAAGTCTTTGTGGTGATCAAGAGATTGATAGTATTTGCAGTGCCGAGCGATCAGATAATGACAAGGAATATCTCATACTCACATTATCCAAAAATGATCTTGACAAAGCGAATAAAGACAAGGCCAACCGATACTTTTCTCCAAAT"
alignments = aligner.align(seq_rab, seq_kan)
for alignment in alignments:
    print(alignment)
score = aligner.score(seq_rab, seq_kan)
score


target            2 SSRLWFSLLLAAAFAGRATALWPWPQNFQTSDQRYVLYPNNFQFQYDVSSAAQPGCSVLD
                  0 |||||||||||||.|||||||||||||.||||||||||||||||||||||||||||||||
query             2 SSRLWFSLLLAAALAGRATALWPWPQNIQTSDQRYVLYPNNFQFQYDVSSAAQPGCSVLD

target           62 EAFQRYRDLLFGSGSWPRPYLTGKRHTLEKNVLVVSVVTPGCNQLPTLESVENYTLTIND
                 60 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
query            62 EAFQRYRDLLFGSGSWPRPYLTGKRHTLEKNVLVVSVVTPGCNQLPTLESVENYTLTIND

target          122 DQCLLLSETVWGALRGLETFSQLVWKSAEGTFFINKTEIEDFPRFPHRGLLLDTSRHYLP
                120 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
query           122 DQCLLLSETVWGALRGLETFSQLVWKSAEGTFFINKTEIEDFPRFPHRGLLLDTSRHYLP

target          182 LSSILDTLDVMAYNKLNVFHWHLVDDPSFPYESFTFPELMRKGSYNPVTHIYTAQDVKEV
                180 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
query           182 LSSILDTLDVMAYNKLNVFHWHLVDDPSFPYESFTFPELMRKGSYNPVTHIYTAQDVKEV

target          242 IEYA

1491.0

In [ ]:
def smith_waterman(ref_seq,query,match,mismatch,W1):

    #Defining matrix (n+1)(m+1)
    H = np.zeros([len(ref_seq) + 1,len(query) + 1])
    zero = 0

    #Defining scoring matrix
    for i in range(1,len(ref_seq) + 1):
        for j in range(1,len(query) + 1):
            if ref_seq[i-1] == query[j-1]:
                H[i,j] = H[i-1,j-1] + match
            else:
                H[i,j] = max(H[i-1,j] - W1,H[i,j-1] - W1,H[i-1,j-1] + mismatch,zero)

    #Isolating Max-value and creating empty aligned sequences
    ref_aligned = []
    query_aligned = []
    i, j = np.unravel_index(H.argmax(),H.shape)
    ref_aligned.append(ref_seq[i-1])
    query_aligned.append(query[j-1])
    score = H[i,j]
    markers = []


    ref_aligned = []
    query_aligned = [ ]
    i,j = np.unravel_index(H.argmax(),H.shape)
    markers = []
    smith_waterman_score = H[i,j]
    while H[i-1,j-1] and H[i-1,j] and H[i,j-1]!= 0:
        score=H[i,j]
        directions = max(H[i-1,j-1],H[i-1,j],H[i,j-1])

        if directions == H[i-1,j-1] and H[i-1,j-1] + match == score:
            ref_aligned.append(ref_seq[i-1])
            query_aligned.append(query[j-1])
            markers.append('|')
            i , j = i - 1 , j - 1 
        elif directions == H[i-1,j-1] and H[i-1,j-1]+mismatch == score:
            ref_aligned.append(ref_seq[i-1])
            query_aligned.append(query[j-1])
            markers.append('.')
            i , j = i - 1 , j - 1 
        elif directions == H[i-1,j] and H[i-1,j] - W1 == score:
            ref_aligned.append(ref_seq[i-1])
            query_aligned.append('-')
            markers.append('-')
            i , j = i - 1 , j 
        elif directions == H[i,j-1] and H[i,j-1] - W1 == score:
            ref_aligned.append('-')
            query_aligned.append(query[j-1])
            markers.append('-')
            i , j = i , j - 1
            
    length=min(len(ref_seq),len(query)) #length of alignment can only be the minimum length of the two sequence
    similarity=(score/(length*match))*100#Similairty is score/maximum match score 
    ref_aligned=''.join(ref_aligned[::-1])#Reverse all list for proper visualisation 
    query_aligned=''.join(query_aligned[::-1])
    markers=''.join(markers[::-1])
    print("Score:", SmithWatermanScore)
    print("Query Sequence is",round(similarity),"%","similar to Referance Sequence")
    i=0
    while i<len(ref_aligned):#while i is less than the length of the aligned sequence
        print('target:',ref_aligned[i:i+60])#print off 60 letters of each sequence and markers
        print('       ',markers[i:i+60])
        print('query: ',query_aligned[i:i+60])
        print()
        i+=60       


        
        
match=3
mismatch=-3
W1=2
ref_seq='MTSSRLWFSLLLAAAFAGRATALWPWPQNFQTSDQRYVLYPNNFQFQYDVSSAAQPGCSVLDEAFQRYRDLLFGSGSWPRPYLTGKRHTLEKNVLVVSVVTPGCNQLPTLESVENYTLTINDDQCLLLSETVWGALRGLETFSQLVWKSAEGTFFINKTEIEDFPRFPHRGLLLDTSRHYLPLSSILDTLDVMAYNKLNVFHWHLVDDPSFPYESFTFPELMRKGSYNPVTHIYTAQDVKEVIEYARLRGIRVLAEFDTPGHTLSWGPGIPGLLTPCYSGSEPSGTFGPVNPSLNNTYEFMSTFFLEVSSVFPDFYLHLGGDEVDFTCWKSNPEIQDFMRKKGFGEDFKQLESFYIQTLLDIVSSYGKGYVVWQEVFDNKVKIQPDTIIQVWREDIPVNYMKELELVTKAGFRALLSAPWYLNRISYGPDWKDFYIVEPLAFEGTPEQKALVIGGEACMWGEYVDNTNLVPRLWPRAGAVAERLWSNKLTSDLTFAYERLSHFRCELLRRGVQAQPLNVGFCEQEFEQT'
query='MASSRLWFSLLLAAALAGRATALWPWPQNIQTSDQRYVLYPNNFQFQYDVSSAAQPGCSVLDEAFQRYRDLLFGSGSWPRPYLTGKRHTLEKNVLVVSVVTPGCNQLPTLESVENYTLTINDDQCLLLSETVWGALRGLETFSQLVWKSAEGTFFINKTEIEDFPRFPHRGLLLDTSRHYLPLSSILDTLDVMAYNKLNVFHWHLVDDPSFPYESFTFPELMRKGSYNPVTHIYTAQDVKEVIEYARLRGIRVLAEFDTPGHTLSWGPGIPGLLTPCYSGSEPSGTFGPVNPSLNNTYEFMSTFFLEVSSVFPDFYLHLGGDEVDFTCWKSNPDIQDFMRKKGFGEDFKQLESFYIQTLLDIVSSYGKGYVVWQEVFDNKVKIRPDTIIQVWREDIPVNYMKELELVTKAGFRALLSAPWYLNRISYGPDWKDFYVVEPLAFEGTPEQKALVIGGEACMWGEYVDNTNLVPRLWPRAGAVAERLWSNKLTSDLTFAYERLSHFRCELLRKSKTKSATGTAAAGCELLRLRSLR'
smith_waterman(ref_seq,query,match,mismatch,W1)       